### ISSUE TITLE
Bug in BCManager

### ISSUE THREAD

**Issue by rcarson3** [llnl/ExaConstit#9]
I was testing out a different set of boundary conditions from my usual symmetric BCs where the loading is in the z direction.

The below case failed:
```toml
[BCs]
    #essential BC ids for the whole boundary
    essential_ids = [1, 2, 3, 6]
    #component combo (x,y,z = -1, x = 1, y = 2, z = 3, xy = 4, yz = 5, xz = 6, free = 0)
    essential_comps = [3, 1, 2, 0, 0, 2]
    #Vector of vals to be applied for each attribute
    #The length of this should be #ids * dim of problem
    essential_vals = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  0.0, 0.001, 0.0]
```
However this case succeeded: 
```toml
[BCs]
    #essential BC ids for the whole boundary
    essential_ids = [1, 2, 3, 4, 5, 6]
    #component combo (x,y,z = -1, x = 1, y = 2, z = 3, xy = 4, yz = 5, xz = 6, free = 0)
    essential_comps = [3, 1, 2, 0, 0, 2]
    #Vector of vals to be applied for each attribute
    #The length of this should be #ids * dim of problem
    essential_vals = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.001, 0.0]
```

The error thrown out was this:
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

Clearly the map was unhappy with having non-sequential indices provided. I'll need to look around and see how the std::map is being used.
